# Generated by Django 5.2.1 on 2025-11-02 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('theme_color', models.CharField(default='#4A90E2', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.area')),
            ],
            options={
                'ordering': ['difficulty', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('game_type', models.CharField(blank=True, choices=[('spelling-challenge', 'Spelling Challenge'), ('punctuation-task', 'Punctuation Task'), ('parts-of-speech', 'Parts of Speech'), ('word-association', 'Word Association'), ('emoji-challenge', 'Emoji Challenge'), ('grammar-check', 'Grammar Check')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='EmojiSentenceItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emoji_data', serialize=False, to='games.gameitem')),
                ('translation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FourPicsOneWordItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fourpics_data', serialize=False, to='games.gameitem')),
                ('answer', models.CharField(max_length=100)),
                ('hint', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartsOfSpeechItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pos_data', serialize=False, to='games.gameitem')),
                ('sentence', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PunctuationItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='punctuation_data', serialize=False, to='games.gameitem')),
                ('sentence', models.TextField()),
                ('hint', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpellingItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spelling_data', serialize=False, to='games.gameitem')),
                ('word', models.CharField(max_length=100)),
                ('sentence', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gameitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.game'),
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('total_images', models.PositiveIntegerField(default=5)),
                ('current_image_index', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiplayer_rooms', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.gameroom')),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('round_index', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group_score', models.IntegerField(default=0)),
                ('evaluated_sentence', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.gameroom')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_or_phrase', models.CharField(max_length=255)),
                ('turn_order', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('was_skipped', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='games.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_score', models.FloatField(default=0)),
                ('coherence_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='games.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='EmojiSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=100)),
                ('emoji_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='games.emojisentenceitem')),
            ],
        ),
        migrations.CreateModel(
            name='FourPicsOneWordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('fourpics_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.fourpicsoneworditem')),
            ],
        ),
        migrations.CreateModel(
            name='PartsOfSpeechWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('pos_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='games.partsofspeechitem')),
            ],
        ),
        migrations.CreateModel(
            name='PunctuationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('mark', models.CharField(max_length=5)),
                ('punctuation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.punctuationitem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gameitem',
            unique_together={('game', 'area', 'difficulty', 'order_index')},
        ),
    ]
