# Generated by Django 5.2.1 on 2025-11-10 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='grammar_data', serialize=False, to='games.gameitem')),
                ('sentence', models.TextField()),
            ],
        ),
    ]
