# Generated by Django 5.2.8 on 2025-11-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_date',
        ),
    ]
