# Generated by Django 5.2.8 on 2025-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
