# Generated by Django 5.2.8 on 2025-11-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='collected_badges',
            field=models.JSONField(blank=True, default=list, help_text='List of collected badge identifiers'),
        ),
    ]
